### ISSUE TITLE
Instructors/Speaker cards for pages

### ISSUE THREAD

**Issue by karthikb351** [hasgeek/events#19]
Add a new front matter value called `instructors`/`speakers` (both should be allowed) section to pages. Useful for workshop/talk pages.

`name`,`image_url`, `bio` fields are compulsory.

```yaml
layout: workshop
instructors:
- name: Rahul Mathur
  image_url: https://images.hasgeek.com/embed/.....
  bio: |
  Engineer @FreeCharge
  Windows and iOS dev
  Alpacas are evil
  url: https://twitter.com/weemundo
```
